[build-system]
requires = ["setuptools>=62.3.0", "wheel", "Cython==0.29.35"]
build-backend = "setuptools.build_meta"

[project]
name = "fgo"
version = "0.1.0"
description = "Frequency Guidance Operator (FGO)."
authors = [
    { name = "Junlin Wang", email = "wangjl@seas.upenn.edu" }
]
readme = "README.md"
license = { text = "MIT" }
requires-python = ">=3.10"

dependencies = [
    "dill==0.3.5.1",
    "diffusers==0.35.2",
    "dm_control==1.0.37",
    "einops==0.8.0",
    "fpsample==1.0.2",
    "gpustat==1.1.1",
    "gymnasium==1.2.3",
    "hydra-core==1.2.0",
    "imageio==2.37.2",
    "ipdb==0.13.13",
    "moviepy==1.0.3",
    "matplotlib==3.10.8",
    "numba==0.58.1",
    "numpy==1.26.4",
    "numcodecs==0.11.0",
    "open3d==0.19.0",
    "omegaconf==2.3.0",
    "patchelf==0.17.2.0",
    "Pillow==12.0.0",
    "scipy==1.15.0",
    "tqdm==4.67.3",
    "termcolor==3.3.0",
    "torch==2.5.1",
    "torchvision==0.20.1",
    "torch-dct==0.1.6",
    "wandb==0.25.0",
    "zarr==2.17.0",
    
    # Third-party local dependencies
    "mujoco-py @ file:third_party/mujoco-py-2.1.2.14",
    "dexart @ file:third_party/dexart-release",
    "gym @ file:third_party/gym-0.21.0",
    "mj_envs @ file:third_party/rrl-dependencies/mj_envs",
    "mjrl @ file:third_party/rrl-dependencies/mjrl",
    "mimicgen @ file:third_party/mimicgen",
    "pytorch3d @ file:third_party/pytorch3d_simplified",
    "robosuite @ file:third_party/robosuite",
]

[tool.setuptools]
include-package_data = true

[tool.setuptools.packages.find]
where = ["."]
include = ["fgo*"]